# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'John Henderson'
tagline:          'Technology Consultant'
description:      'JH Technology Blog'
url:              'http://john-henderson.github.io/myblog3'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
  
# Author Details
author:         'John Henderson'
linkedin:       'https://www.linkedin.com/pub/john-henderson/a2/559/573'
twitter:        'https://twitter.com/John_Henderson_'
facebook:       'https://www.facebook.com/shopjohn'
#gplus:          'https://plus.google.com/100425464897246255887/'

# Google Analytics
gahandler: 'UA-52149651-1'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 3 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.8

exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]